name: Checks
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    name: Checking size
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Check size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  storybook:
    runs-on: ubuntu-latest
    name: Checking storybook
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i
      - name: Check storybook
        run: npm run build-storybook
